const request = require('supertest');
const express = require('express');
const { newDb } = require('pg-mem');

let dbManager;
let app;

function setupDatabase() {
  const mem = newDb({ autoCreateForeignKeyIndices: true });
  const adapter = mem.adapters.createPg();
  global.__LATE_POOL_FACTORY = () => new adapter.Pool();
  jest.resetModules();
  dbManager = require('../config/database');
}

async function ensureSchema() {
  const db = dbManager.getDatabase();

  await db.exec('DROP TABLE IF EXISTS messages CASCADE;');
  await db.exec(`
    CREATE TABLE IF NOT EXISTS messages (
      id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      call_date TEXT,
      call_time TEXT,
      recipient TEXT,
      recipient_user_id INTEGER,
      sender_name TEXT,
      sender_phone TEXT,
      sender_email TEXT,
      subject TEXT,
      message TEXT,
      status TEXT,
      callback_time TEXT,
      notes TEXT,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );
  `);

  const valuePlaceholders = Array.from({ length: 11 }, (_, index) => dbManager.placeholder(index + 1)).join(', ');

  const insert = db.prepare(`
    INSERT INTO messages (
      call_date, call_time, recipient, sender_name,
      sender_phone, sender_email, subject, message,
      status, callback_time, notes, created_at, updated_at
    ) VALUES (${valuePlaceholders}, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id
  `);

  await insert.get(['2025-01-01', '09:00', 'Equipe A', 'João', null, null, 'Aviso', 'Mensagem 1', 'pending', null, null]);
  await insert.get(['2025-01-02', '10:30', 'Equipe B', 'Maria', null, null, 'Aviso', 'Mensagem 2', 'resolved', null, null]);
}

beforeAll(async () => {
  setupDatabase();
  await ensureSchema();

  const apiRoutes = require('../routes/api');
  app = express();
  app.use(express.json());
  app.use((req, _res, next) => {
    req.session = {
      user: {
        id: 1,
        name: 'Test User',
        role: 'ADMIN',
      },
    };
    next();
  });
  app.use('/api', apiRoutes);
});

afterAll(async () => {
  await dbManager.close();
  jest.resetModules();
  delete global.__LATE_POOL_FACTORY;
});

test('orders messages by id descending', async () => {
  const res = await request(app).get('/api/messages');
  expect(res.status).toBe(200);
  expect(res.body.success).toBe(true);
  const ids = res.body.data.map(m => m.id);
  expect(ids).toEqual([2, 1]);
});
